### ISSUE TITLE
klte recovery broken

### ISSUE THREAD

**Issue by EfxBDhT8** [Divested-Mobile/DivestOS-Build#11]
Hi, the current recovery image for klte doesn't boot. The older images boot fine.

**Comment by SkewedZeppelin** [comment]
Yep, I can reproduce.

**Comment by SkewedZeppelin** [comment]
Good news,

At least you can trivially flash a new boot.img via heimdall.
And I cannot reproduce it on mako, flox, or d852, so it isn't
widespread.

Bad news, will break next OTA install and users will have to flash via
heimdall.

**Comment by SkewedZeppelin** [comment]
I have fixed this.

klte when booted to recovery has an extremely long commandline passed to the kernel by the bootloader.
With the recent addition of slub_nomerge it was too long.

I now set slub/slab_nomerge in the code instead of the commandline as of 083e2048f8d40c66c76c182165abb75487091d92.
And tested klte booting. The build is uploading and will be up in a few minutes.

**Comment by EfxBDhT8** [comment]
Thanks for fixing this issue.
