### ISSUE TITLE
OnePlus 7 Pro - Post Install - MULL missing & cannot install

### ISSUE THREAD

**Issue by ToddCrimson** [Divested-Mobile/DivestOS-Build#114]
Freshly installed DivestOS.

Cannot find Mull as an installed app. 
F-Droid shows installed, but cannot find it anywhere.
Tried under apps / show system apps, no luck
Tried downloading the APK directly, by downloading an alternative browser (Fennec) 
Got the APK, but won't let me install, as it says it is already installed.

So Mull is somewhere in the system, installed but disabled.

Any idea how to make it work?

**Comment by SkewedZeppelin** [comment]
Only a shim version of Mull is installed due to space constraints.

F-Droid is supposed to prompt you to update it on first run, however due to Mull
being in the DivestOS F-Droid repo and the official F-Droid repo it sometimes
will not suggest the update and you have to manaually search for Mull in F-Droid
and install it.

**Comment by ToddCrimson** [comment]
OK thanks, the shim part explanation helps.
Manually searching for Mull on F-Droid just shows Mull but with no buttons to open / install or remove. 

I tried force stopping F-Droid, clearing Cache and Data, and the restarting F-Droid.
Voila, it started downloading Mull, and then wanted permission toggle to install apps from F-Droid
Was a bit tricky as the window wouldn't go away. But once I toggeld it one, killed the app, went back in.

It all has started working.
