### ISSUE TITLE
OnePlus 7 Series Firmware Issue Fun

### ISSUE THREAD

**Issue by tommytran732** [Divested-Mobile/DivestOS-Build#167]
I tried updating from the October build to the November build, and it failed to apply the update. I then proceeded to unlock the bootloader, adb sideloaded the November build, and relocked it. It's soft bricked and gave "The current image (boot/recovery) have been destroyed and cannot boot". Maybe it wasn't signed properly or the firmware changed?

It does boot just fine with an unlocked bootloader.

**Comment by SkewedZeppelin** [comment]
The newer firmware for OP7 may no longer support locking like is known on OP8 and OP9.

**Comment by redfoot0** [comment]
I also have the same update issue on guacamole.
If the firmware has the same issue as the op8 and 9 series, can the newer/broken firmware be left off?

**Comment by SkewedZeppelin** [comment]
There are two issues here:

The first is being unable to install the update, I recevied a log for this:
```
11-13 18:31:11.601  1308  1308 I update_engine: [INFO:partition_writer_factory_android.cc(44)] Virtual AB Compression disabled, using Partition Writer for `LOGO`
11-13 18:31:11.604  1308  1308 I update_engine: [INFO:partition_writer.cc(295)] Opening /dev/block/bootdevice/by-name/LOGO_b partition without O_DSYNC
11-13 18:31:11.602  1308  1308 W update_engine: type=1400 audit(0.0:78550): avc: denied { read } for name="sde47" dev="tmpfs" ino=22012 scontext=u:r:update_engine:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=0
11-13 18:31:11.608  1308  1308 E update_engine: [ERROR:utils.cc(530)] Opening block device /dev/block/bootdevice/by-name/LOGO_b: Permission denied (13)
11-13 18:31:11.612  1308  1308 I update_engine: [INFO:partition_writer.cc(100)] Caching writes.
11-13 18:31:11.617  1308  1308 E update_engine: [ERROR:partition_writer.cc(104)] Unable to open file /dev/block/bootdevice/by-name/LOGO_b: Permission denied (13)
11-13 18:31:11.612  1308  1308 W update_engine: type=1400 audit(0.0:78551): avc: denied { read write } for name="sde47" dev="tmpfs" ino=22012 scontext=u:r:update_engine:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=0
11-13 18:31:11.621  1308  1308 E update_engine: [ERROR:partition_writer.cc(300)] Unable to open target partition LOGO on slot B, file /dev/block/bootdevice/by-name/LOGO_b
```

Which shouldn't happen: https://review.lineageos.org/c/LineageOS/android_hardware_oplus/+/340515

The second issue is that the new 12 firmware likely did remove relock support.
I can remove the firmware inclusion for OP7 series, but then users either end up:
- on outdated/insecure 11 firmware with bugs, since userspace blobs are expecting 12
- on latest 12 firmware, with no relock support

**Comment by SkewedZeppelin** [comment]
> adb sideloaded 

you can `adb sideload` while locked, you just can't `fastboot update`

**Comment by darhma** [comment]
> 
>     * on outdated/insecure 11 firmware with bugs, since userspace blobs are expecting 12
> 
>     * on latest 12 firmware, with no relock support
Personally I think the second option is preferable

**Comment by tommytran732** [comment]
Well, the Pixel 7T is EOL anyways. The firmware will quickly become outdated/insecure as well.

So I guess the question is whether there are any serious vuln that has been fixed between March (which was previously included in the October build) and August.

**Comment by SkewedZeppelin** [comment]
New 19.1 builds are up for OnePlus 7 series with firmware removed so users can choose.

Firmware is still included on OP8/9.

**Comment by tommytran732** [comment]
> New 19.1 builds are up for OnePlus 7 series with firmware removed so users can choose.
> 
> Firmware is still included on OP8/9.

What about the 20 builds?

**Comment by SkewedZeppelin** [comment]
I'll compile 20.0 with firmware removed another day.

**Comment by tommytran732** [comment]
> I'll compile 20.0 with firmware removed another day.

Oh, and I wonder if you have the firmware for the OP7T posted somewhere or should I go ahead and extract it from the stock OS myself?

**Comment by SkewedZeppelin** [comment]
I'm re-opening this. I just received a report of non-functional touch/screen on guacamole.

I've added some warnings here: https://divestos.org/index.php?page=news#2022-11

**Comment by tommytran732** [comment]
Ah fun. Divest 20 runs just fine on my 7T with the Android 12 firmware.

**Comment by darhma** [comment]
> Ah fun. Divest 20 runs just fine on my 7T with the Android 12 firmware.

so with the bootloader unlocked?

**Comment by SkewedZeppelin** [comment]
I've pulled all the OP7 series builds.

Any users who upgraded to yesterdays 19.1 builds with A11 firmware installed and have no touch screen should flash A12 firmware if they are unlocked.

Otherwise they unlock, flash the previous build, and restore from backup.

Old builds are available here: https://divestos.org/builds/old/old.txt

I will fix the flashing issue and include A12 firmware back for the next builds.
Users that are locked will have to migrate regardless.

**Comment by theotheroracle** [comment]
so if i understand correctly, all op7 users have to unlock their bootloader ?

**Comment by tommytran732** [comment]
Yes

**Comment by SkewedZeppelin** [comment]
New builds are uploading: https://divestos.org/index.php?page=news#XXXX-XX

**Comment by SkewedZeppelin** [comment]
@hbarthel 
you need to manually adb sideload the latest version, should get you back going without any loss since you're unlocked

fix your adb, to access fastboot use volume up + power, to access recovery use volume down + power

also to force most modern devices off can usually use volup+voldown+power, and next time don't wait a week before asking for help :wink:

**Comment by Tecol87** [comment]
I just flashed the latest DivestOS on my OnePlus 7 (guacamoleb) according to the instructions (new install).
The touchscreen does work correctly on slot b, but does not work on slot a. Also the boot takes way longer on slot a (but succeeds). It hangs at the "You are booting a different OS".
The device is in unlocked state.

**Comment by Tecol87** [comment]
My touchscreen did not work on slot a (but on slot b) after the first installation. I re-did the installation and re-formatted /data multiple times, after then it works now on both slots.

Is there an easy way to restore locking-support?
I consider a locked outdated-device more secure than an unlocked device. I don't mind building it myself.

**Comment by Tecol87** [comment]
@SkewedZeppelin 
Thank you very much
