### ISSUE TITLE
Support for the Amazon Fire HD 8 2018

### ISSUE THREAD

**Issue by Username58260** [Divested-Mobile/DivestOS-Build#21]
Is it possible to add support for the Fire HD 8 2018?

- [x] bootloader has been unlocked and has working TWRP [(XDA Developers)](https://forum.xda-developers.com/t/unlock-root-twrp-unbrick-fire-hd-8-2018-karnak-amonet-3.3963496/)
- [x] unofficial [LineageOS 18.1](https://forum.xda-developers.com/t/rom-unstable-unlocked-karnak-lineage-18-1-25-october-2021.4352241/) 

LineageOS 18.1 currently says "UNSTABLE" but besides a few codec issues it seems to be stable,

Updates are rather infrequent and due to the way the exploit works OTA updates might not be possible, if support is added i would be willing to test builds.

**Comment by SkewedZeppelin** [comment]
That tree is permissive selinux. Absolute no go for DivestOS.

The DivestOS deblobber doesn't have any known MediaTek blobs.

Also the kernel is 3.19, DivestOS CVE patcher can't fully patch such a kernel
due to being non-LTS. I could probably hardcode 3.19 version to 3.18 patches,
but still not with the huge permissive issue.

MediaTek support in DivestOS will largely never be great as LineageOS is far
more Qualcomm AOSP (CAF) than it is regular AOSP.
