### ISSUE TITLE
Don't work for Pixel 6a (bricked!)

### ISSUE THREAD

**Issue by Netobaia** [Divested-Mobile/DivestOS-Build#228]
Hi, I need your help! I can't install DivestOS on Pixel 6a. See the result on flash fastboot file:

extracting android-info.txt (0 MB) to RAM...
Checking 'product'                                 OKAY [  0.000s]
Setting current slot to 'b'                        OKAY [  0.103s]
extracting boot.img (64 MB) to disk... took 0.209s
archive does not contain 'boot.sig'
Sending 'boot_b' (65536 KB)                        OKAY [  2.169s]
Writing 'boot_b'                                   OKAY [  0.301s]
extracting dtbo.img (16 MB) to disk... took 0.037s
archive does not contain 'dtbo.sig'
Sending 'dtbo_b' (16384 KB)                        OKAY [  0.553s]
Writing 'dtbo_b'                                   OKAY [  0.060s]
archive does not contain 'dt.img'
archive does not contain 'recovery.img'
extracting vbmeta.img (0 MB) to disk... took 0.000s
archive does not contain 'vbmeta.sig'
Sending 'vbmeta_b' (8 KB)                          OKAY [  0.000s]
Writing 'vbmeta_b'                                 OKAY [  0.002s]
archive does not contain 'vbmeta_system.img'
extracting super_empty.img (0 MB) to disk... took 0.000s
Rebooting into fastboot                            OKAY [  0.000s]
< waiting for any device >

And now, I cannot access the recovery mode! Please, I put all my money in that because I had hope in that project!

**Comment by SkewedZeppelin** [comment]
bluejay is my daily driver, it works just fine.
someone in chat even installed it just fine in chat yesterday.

you cannot brick your device during the unlock or install process

your issue here is very likely just wrong tool or drivers on your system

please ensure you have the correct android platform tools as described here: https://divestos.org/pages/bootloader#prereqComputer

you can monitor device connections via: `sudo dmesg -w`
you need to make sure the device is visible via `fastboot devices` if in bootloader or `adb devices` if in recovery
you may need to run fastboot or adb as root for the device to be seen
you may need to use a usb 2.0 port or a usb hub if you don't have any usb 2.0 ports

**Comment by Netobaia** [comment]
I'm use Pop!OS and recognized the device with no problem. Only in the moment of "fastboot update divested-20.0-20230719-dos-bluejay-fastboot.zip" causes that. 

You have any solution? How I make it work, after this screen above?

**Comment by Netobaia** [comment]
Ok, I tryed in other Linux System (Linux Mint) and process work fine.
I will close the issue. Thanks!

**Comment by SkewedZeppelin** [comment]
Glad to hear
