### ISSUE TITLE
F-Droid asks the user for permission to install and update apps on DivestOS 19.1

### ISSUE THREAD

**Issue by EmanuelLoos** [Divested-Mobile/DivestOS-Build#87]
When installing an app on DivestOS 19.1, F-Droid uses the old way of installing apps on Android without being the preinstalled app store, which requires the user to confirm every time. Consider adding the privileged extension until F-Droid supports the new API.
![Screenshot_20220423-101627_Paketinstallation](https://user-images.githubusercontent.com/29912739/164889672-3fdf0238-c062-4316-9b96-cf4044b92da5.png)

**Comment by SkewedZeppelin** [comment]
This is expected, please read the changelog. FDroidPrivExt was removed.

**Comment by EmanuelLoos** [comment]
Oh, sorry again for not looking there before. It is still an issue, though ... isn't it? Therefore: Should I leave this one open?

**Comment by SkewedZeppelin** [comment]
You can leave this open, I'll rename it later.
I am still on the fence on whether or not I'll add back FDroidPrivExt.

There are two issues:
- the AndroidManifest mismatch due to recently added per-app sensors permission
- the fact that FDroid and PrivExt are super old targerSdkVersions

I can probably easily patch the first issue, but the second issue requires lots
of work upstream.

**Comment by EmanuelLoos** [comment]
Other F-Droid clients include:

- [SkyDroid](https://github.com/redsolver/skydroid)
- Droid-ify

It would probably be a good idea to change the default repositories to only include free ones if using them.

**Comment by SkewedZeppelin** [comment]
I have no intent on shipping an alternative F-Droid client.
All of them have worse issues of their own.

**Comment by SkewedZeppelin** [comment]
FDroidPrivExt will not be added back at this time.
